### ISSUE TITLE
URL to “See the post” should be a direct URL to the comment by u/Mr-Molester

### ISSUE THREAD

**Issue by justsomeguyhelping** [licensedprism1/driveyouradblockcounterup#2]
EXPECTED BEHAVIOR: The “See the post” button should take you directly to the Reddit comment where u/Mr-Molester announced he had bought the domain.
ACTUAL BEHAVIOR: Takes the user to the full post, which does not directly talk about this website.
STEPS TO REPRODUCE: Click the “See the post” button on the website.

The URL that should be linked: https://www.reddit.com/r/assholedesign/comments/8fmitr/comment/dy4x2gc?st=JGL9JEW2&sh=2e2fb312

**Comment by AbrahamMast** [comment]
Fixed it

**Comment by licensedprism1** [comment]
Commited to main website.
